require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'Busfeed' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'react-native-maps', :path => '../node_modules/react-native-maps'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-spinkit', :path => '../node_modules/react-native-spinkit'

  target 'BusfeedTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({'Flipper' => '0.79.0'})
  post_install do |installer|
    flipper_post_install(installer)
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
        end
        targets_to_ignore = %w(React yoga)
        
        if targets_to_ignore.include? target.name
          target.remove_from_project
        end
    end
  end
end

# target 'Busfeed-tvOS' do
#   # Pods for Busfeed-tvOS

#   target 'Busfeed-tvOSTests' do
#     inherit! :search_paths
#     # Pods for testing
#   end
# end
